academics/urls.py
from django.urls import path
from .views import program, index, facility, scholarship, contact_us, about_us

"""
 This module contains all the possible urls configured for users_app.
"""

urlpatterns = [
    path('', index, name='index'),
    path('programs/<int:code>', program, name='programs'),
    path('facilities/', facility, name='facility'),
    path('scholarships/', scholarship, name='scholarship'),
    path('contact-us/', contact_us, name="contact_us"),
    path('about-us/',about_us, name="about_us")
]

ncit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('academics.urls')),
    path('notices/', include('notices.urls')),
    path('gallery/', include('image_gallery.urls')),
    path('accounts/',include('accounts.urls')),
    path('manage/', admin.site.urls),

]

if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

academics/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.urls import reverse

"""
    All the database entities of users_app are described in this module.
"""

class Program(models.Model):
    """
     Program model represents different programs like BE Software, BE Civil, BE IT and so on.

     Each Program has its unique code.

     Each Program has different semesters; for master programs 4 semesters and for bachelor
     programs 8 semesters. Semester is represented by another model/table. Program and Semester
     has one-to-many relationship i.e One program has many semesters but particular semester
     belongs to only one program.
     """

    name = models.CharField(max_length=100)
    code = models.IntegerField()
    desc = models.TextField(default="", blank=True)
    career_prospectus = models.TextField(default="", blank=True)

    def __str__(self):
        """
         :return: Readable representation of program object
        """
        return f'{self.name}'


    def get_absolute_url(self):
        """
        :return: url to the program specified by code as program/{code}
        """

        return reverse('programs', args=(26,))  # Displaying BE Software for all courses , should be changed



class Subject(models.Model):
    """
        Subject model represents the subjects of a particular semester/program.

        Each Subject has unique code.

        A semester has multiple subjects and similarly, a single subject, say Logic Circuit(Elx 110)
        belongs to 2nd Semester (of BE Software) and 3rd Semester (of BE IT) . So, Subject and Semester
        shows many-to-many relationship.

        Program and Subject are related through Semester. For example; if we want all the subjects of
        BE Software, then we have to retrieve each Semester of BE Software and from those individual semester,
        we can get the subjects.

        To ease the above process, we introduce the many-to-many relationship between Program and Subject.
        Now we can directly access the subjects of BE Software without joining Semester.

    """
    code = models.CharField(max_length=10, default='N/A')
    name = models.CharField(max_length=100)
    credit = models.IntegerField()
    programs = models.ManyToManyField(Program)

    def __str__(self):
        """
       :return: Readable representation of subject object
     """
        return f'{self.name}'



class Semester(models.Model):
    """
      Semester model represents the different semesters in the particular program.

      `sem` gives the semester  as 1, 2 , 3 and so on.

      Semester is related to Program model by a foreign key.

      Each Semester has different subjects related by field `subjects`.

    """
    sem = models.IntegerField(
        validators=[
            MaxValueValidator(8),
            MinValueValidator(1)
        ])

    subjects = models.ManyToManyField(Subject)
    program = models.ForeignKey(Program, on_delete=models.CASCADE)



    def get_meaningful_name(self):
        """

        :return: meaningful names for the given semester. Example, First(I) for 1, Second(II) for 2 and so on.
        """
        names = {
            1: "First (I)",
            2: "Second (II)",
            3: "Third (III)",
            4: "Fourth (IV)",
            5: "Fifth (V)",
            6: "Sixth (VI)",
            7: "Seventh (VII)",
            8: "Eight (VIII)"
        }
        return names.get(self.sem)


    def __str__(self):
        """
        :return: Readable representation of semester object
      """
        return f'{self.program} - {self.sem} sem'


class Message(models.Model):
    """
    Message model for contact us form.
    """
    email = models.EmailField()
    name = models.CharField(max_length=100)
    message = models.TextField()
    date = models.DateTimeField()
    def __str__(self):
        return self.name

academics/forms.py
from django import forms
from .models import Message
class ContactUsForm(forms.ModelForm):
    class Meta :
        fields = ['email','name','message']
        model = Message

academics/views.py
from django.shortcuts import render
from .models import Program, Semester, Message
from .forms import ContactUsForm
from django.utils import timezone

"""
    This module contains the methods and classes to handle HTTPRequest and 
    generate appropriate HTTPResponse.
"""


def program(request, code):
    """
    :type request: HTTPRequest
    :param request: carries request info

    :type code: int
    :param code: program code

    -> filters out the program on the basis of given program code

    -> if no program exists with that code, return 404

    -> otherwise, render program.html with context current_program


    """
    current_program = Program.objects.get(code=code)

    if current_program is None:
        return render(request, 'academics/404.html', {'error': '404 Page Not Found '})


    return render(request, 'academics/program.html', {'current_program': current_program})


def index(request):
    """

    :type request: HTTPRequest
    :param request: carries request info
    :return: renders index.html

    """
    return render(request, 'academics/index.html')


def facility(request):
    """

        :type request: HTTPRequest
        :param request: carries request info
        :return: renders facilities.html

        """
    return render(request, 'academics/facilities.html')


def scholarship(request):
    """

        :type request: HTTPRequest
        :param request: carries request info
        :return: renders scholarship.html

        """
    return render(request, 'academics/scholarship.html')


def handle404(request):
    """

           :type request: HTTPRequest
           :param request: carries request info
           :return: renders 404.html

           """
    return render(request, 'academics/404.html', {'error': '404 Page Not Found'})


def about_us(request):
    return render(request, 'academics/about.html')


def contact_us(request):
    newform = ContactUsForm()
    if request.method=='POST':
        form = ContactUsForm(data=request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.date = timezone.now()
            message.save()
            return render(request, 'academics/contact-us.html', {'success' : True,'form':newform})
        else:
            return render(request, 'academics/contact-us.html', {'form' : form})
    else:
        return render(request, 'academics/contact-us.html', {'form' : newform})

academics/templates/academics/about.html
{% extends 'academics/base.html' %}
{% load static %}
{% block content %}
 <h2 class="navy mb-5 heading">About Us </h2>
        <div class="para">
              <p>
                <span class="bold">Nepal College of Information  Technology – NCIT</span>, established in 2001,
                 runs Pokhara University-affiliated Bachelor’s and Master’s programs – BE, BBA, ME, MSc & MCIS.
                Our  Engineering Degrees are approved by  the Nepal Engineering Council. It has  produced over
                a thousand engineers  since its establishment.
               </p>


             <p>   NCIT, a pioneer private institution  providing engineering education in  Nepal, is renowned for  excellence in  teaching & research, while maintaining  close and mutually beneficial links  with various sectors. The College  provides excellent higher education  opportunities and nurtures individual  talent using an applicable knowledge  base that fully supports ongoing social  changes and economic advances.
                The institution is committed to providing quality education  in various engineering disciplines
                 keeping in mind  emerging professional needs. Our highly qualified and  experienced faculty is
                  fully dedicated to their teaching. We  have a state-of-the-art infrastructure to foster academic  excellence. Moreover, we provide vital non-credit inputs  including research & project work, supplementing the  regular
                courses to meet the diverse learning needs of its  students and improve their
                employability.</p>

                <p>
                    <img class="para-image" src="{% static 'academics/images/carousel/building.jpg' %}" alt="">
                </p>

        <p>
            The College is also an authorized training partner of  CISCO, Red Hat, and Microsoft.
            It provides related- training and conducts preparatory examinations leading to internationally
             recognized certifications from these  renowned institutions. NCIT has MOUs with the Microsoft
              Innovation Center and many reputed multinational and  local companies for internships and
              training programmers.

        </p>
                <p>
                NCIT envisions an institutional role for itself beyond  academic boundaries.
                It takes the aspirations and future  success of its students as pathway to nation building.
               </p>

        </div>


{% endblock %}

academics/templates/academics/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Ncit - Nepal College of Information Technology</title>
  <base href="/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="{% static 'academics/images/logo-title.png' %}">
  <link href="https://fonts.googleapis.com/css2?family=Lora&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@300&display=swap" rel="stylesheet">
   <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

   <link rel="stylesheet" href="{% static 'academics/css/reset.css' %}"/>
    <link rel="stylesheet" href="{% static 'academics/css/footer.css' %}"/>




</head>
<body>
     {% include 'academics/header.html' %}

      <div class="container">
         <div class="row">
            <div class="col-lg-8 main">
               {% block content%}{% endblock %}    <!-- Main Body-->
            </div>
             {% block side-bar %}
             <div class=" col-lg-4 ">
                   {% include 'academics/side_bar.html' %}  <!-- side bar-->
             </div>
             {% endblock %}
        </div>
    </div>

   {% include 'academics/footer.html' %}


  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

    <script>
      $(document).ready(function(){
       $('.carousel').carousel({
        keyboard:true,
        interval:1000
       })
    });

   </script>



</body>
</html>

academics/templates/academics/contact-us.html
{% extends 'academics/base.html' %}
{% load widget_tweaks%}
{% block content %}
<h2 class="navy heading">Contact Us</h2>
<div class="course-desc mt-5">

    {% if success%}
        <div class="alert alert-success">
            Your message has been sent, Thank you.
        </div>
    {% endif %}

    <form action="/contact-us/" method="POST" novalidate>
        {% csrf_token %}

        {% for hidden_field in form.hidden_fields %}
            {{ hidden_field }}
        {% endfor %}

        {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
            {% for error in form.non_field_errors %}
                {{ error }}
            {% endfor %}
            </div>
        {% endif %}

        {% for field in form.visible_fields %}
            <div class="form-group">
            {{ field.label_tag }}

            {% if form.is_bound %}
                {% if field.errors %}
                {% render_field field class="form-control is-invalid" %}
                {% for error in field.errors %}
                    <div class="invalid-feedback">
                    {{ error }}
                    </div>
                {% endfor %}
                {% else %}
                {% render_field field class="form-control is-valid" %}
                {% endif %}
            {% else %}
                {% render_field field class="form-control" %}
            {% endif %}

            {% if field.help_text %}
                <small class="form-text text-muted">{{ field.help_text }}</small>
            {% endif %}
            </div>
        {% endfor %}
        <input type="submit" value="submit" class="btn btn-primary btn-lg">
    </form>
</div>
{% endblock %}

academics/templates/academics/error.html
{% extends 'academics/base.html' %}

{% block content %}
   <h2>{{ error }}</h2>
   <p class="para mt-3">The resource you are requesting for doesnot exist in this server</p>
   <a href="/" class="btn btn-primary" style="color:white;">Back To Home </a>
{% endblock %}

academics/templates/academics/facilities.html
{% extends 'academics/base.html' %}

{% block content %}
 <h2 class="navy heading">Facilities</h2>

   <div class="course-desc mt-5">
       <p class="heading">Library</p>
       <p class="para ">
           NCIT has a spacious library of over 20,000 books including textbooks,
           reference, research & project reports, and audio-visual materials.
           Online access to international library networks and latest top journals,
           magazines, and newspapers is available. The library timing is 6:30am– 8:30pm,
           Sunday to Friday, for students to be able to do long study.
       </p>
   </div>

<div class="course-desc mt-5">
       <p class="heading">ICT</p>
       <p class="para">
          NCIT has a networked environment with a centrally located ICT
           – Information Communication Technology – Centre with uninterrupted
           internet connectivity and free WIFI. The College also has state-of-the-art
           computer labs to encourage e-learning and enhance computer skills so
           necessary in the contemporary knowledge socio-economy.


       </p>
   </div>

<div class="course-desc mt-5">
       <p class="heading">Canteen</p>
       <p class="para">
          The College has a fine canteen for students and employees
           in its premises. At NCIT, the food and beverage including
           free drinking water quality is checked cautiously – periodically
           or randomly and physically or scientifically.
           We ensure that all food items are fresh, clean, nutritious,
           chemical or pest-free, and as affordable as feasible.


       </p>
   </div>

<div class="course-desc mt-5">
       <p class="heading">Virtual Classes & Conferences</p>
       <p class="para">
         NCIT provides Virtual Classes for lectures, assignments,
           tutorials & note taking. These help learning better through
           digital inputs & outputs and greatly reinforce classroom teaching
           & self-study. Conference halls facilitate organizing lectures and
           conferences that are regular events on the campus. The halls are
           equipped with the latest educational technology for webinars and
           online workshops.
       </p>
   </div>


<div class="course-desc mt-5">
       <p class="heading">Project Labs</p>
       <p class="para">
        NCIT has cutting edge labs for project work & research.
           Students can put their theoretical knowledge to use and
           learn to work independently. Modern equipment allows students
           to apply theory to function and to do research.


       </p>
   </div>

{% endblock%}

academics/templates/academics/footer.html
  <footer>
      <div class="container">
          <div class="row">
              <div class="col-6 col-sm-6 col-lg-3 div-center">
                 <p class="footer-heading">College</p>
                 <ul style="list-style:none;">
                  <li><a class="text-muted" href="{% url 'index' %}">Home</a></li>
                  <li><a class="text-muted" href="{% url 'facility' %}">Facilities</a></li>
                  <li><a class="text-muted" href="{% url 'gallery' %}">Gallery</a></li>
                  <li><a class="text-muted" href="">Admission</a></li>
                   <li><a class="text-muted" href="{% url 'about_us' %}">About Us</a></li>
                 </ul>

              </div>
              <div class="col-6 col-sm-6 col-lg-3 div-center">
                <p class="footer-heading">Academics</p>
                 <ul style="list-style:none;">
                  <li><a class="text-muted" href="{% url 'programs' 26 %}">Programs</a></li>
                  <li><a class="text-muted" href="{% url 'scholarship' %}">Scholarships</a></li>
                  <li><a class="text-muted" href="{% url 'notices' %}">Notices</a></li>
                  <li><a class="text-muted" href="">Faculties</a></li>
                     <li><a class="text-muted" href="{% url 'facility' %}">Facilities</a></li>
                 </ul>

              </div>
               <div class="mbl-margin col-sm-6 col-lg-3 div-center">
                 <p class="footer-heading">Find Us</p>
                 <ul style="list-style:none;">
                 <li class="text-muted"> <i class="fa fa-phone" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;01-828837 </li>
                 <li class="text-muted"> <i class="fa fa-envelope" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;info@ncit.edu.np</li>
                  <li class="text-muted"><i class="fa fa-map-marker" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;Balkumari, Lalitpur</li>
                 </ul>

              </div>
               <div class="mbl-margin col-sm-6 col-lg-3 div-center">
                 <p class="footer-heading">Account</p>
                 <ul style="list-style:none;">
                 <li><a class="text-muted" href="{% url 'login' %}">
                     <i class="fa fa-sign-in" aria-hidden="true"></i> Login </a>
                 </li>
                 <li><a class="text-muted" href="{% url 'register' %}">
                         <i class="fa fa-user" aria-hidden="true"></i> Register </a>
                 </li>

                 </ul>

              </div>

              </div>
          </div>


      </div>



        <p class="footer-text pt-5 text-muted">Copyright {% now 'Y' %} &copy; Nepal College of Information Technology</p>
  </footer>

academics/templates/academics/header.html
{% load static %}
<div class="login-banner mb-3">
    <div class="left">
       <a href=""><i class="fa fa-phone ml-5" aria-hidden="true"></i>01-828837</a>
        <a href=""> <i class="fa fa-envelope" aria-hidden="true"></i>info@ncit.edu.np</a>
        <a href=""><i class="fa fa-map-marker" aria-hidden="true"></i>Balkumari, Lalitpur</a>
    </div>
        <div class="right">
            <a class="" href="{% url 'login' %}"><i class="fa fa-sign-in" aria-hidden="true"></i> Login </a>
            <a class="mr-5" href="{% url 'register' %}"><i class="fa fa-user" aria-hidden="true"></i> Register </a>
        </div>

</div>


  <div class="logo mt-2">

        <a class="navbar-brand" href="/"><img class="logo" src="{% static 'academics/images/logo.png' %}" alt=""></a>

  </div>

 <nav class="navbar navbar-expand-lg navbar-light">

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto links mt-4">
          <li class="nav-item">
              <a class="nav-link" href="/">Home </a>
         </li>
           <li class="nav-item">
              <a class="nav-link" href="{% url 'facility' %}">Facilities </a>
         </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
             Programs
            </a>
            <ul class="dropdown-menu drop-links">
                {% for program in programs %}
               <li class="dropdown-item">
                   <a class="dropdown-item" href=" {{program.get_absolute_url}}">
                       {% if current_program.name == program.name%}
                        <span class="text-muted">{{program.name}}</span>
                       {% else %}
                       <span >{{program.name}}</span>
                       {% endif %}
                   </a>
                </li>
                {% endfor %}
             </ul>
        </li>
          <li class="nav-item dropdown">
               <a class="nav-link dropdown-toggle" href="#"  role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
             Admission
            </a>
            <ul class="dropdown-menu">
               <li class="dropdown-item">
                   <a class="dropdown-item" href="{% url 'scholarship' %}">Scholarships</a>
               </li>
            </ul>
          </li>
          <li class="nav-item">
              <a class="nav-link" href="{% url 'notices' %}">Notice </a>
         </li>
          <li class="nav-item">
              <a class="nav-link" href="{% url 'gallery' %}">Gallery </a>
         </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'contact_us' %}">Contact </a>
          </li>
          <li class="nav-item lg-hidden">
               <a class="nav-link text-info" href="{% url 'login' %}"><i class="fa fa-sign-in" aria-hidden="true"></i> Login </a>
          </li>
          <li class="nav-item lg-hidden">
              <a class="nav-link text-info" href="{% url 'register' %}"><i class="fa fa-user" aria-hidden="true"></i> Register </a>
          </li>

      </ul>
    </div>
  </nav>

academics/templates/academics/program.html
{% extends 'academics/base.html' %}

{% block content %}
   <h2 class="navy heading">{{current_program.name}}</h2>

<!--    Remove this line later, only for demo-->

  <small style="background:#00FFFF;">This is the sample page for all programs</small>

  {% if current_program.desc %}
   <div class="course-desc mt-5">
       <p class="heading">Course Description</p>
       <p class="para">{{current_program.desc}}</p>
   </div>
 {% endif %}

  {% if current_program.career_prospectus %}
   <div class="course-career mt-5">
        <p class="heading">Career Prospectus</p>
       <p class="para">{{current_program.career_prospectus}}</p>
   </div>
  {% endif %}

   <div class="course-structure mt-5">
        <p class="pb-3 heading">Course Structure</p>
       <div id="accordion">

         {% for semester in current_program.semester_set.all %}


        <div class="card mb-3">
          <div class="card-header" id="">
            <h5 class="mb-0">
              <button class="btn btn-link btn-black" data-toggle="collapse" data-target="#collapse{{semester.sem}}" aria-expanded="false" aria-controls="collapse{{semester.sem}}">
               {{semester.program.name}} -  {{semester.get_meaningful_name}} Semester
              </button>
            </h5>
          </div>

          <div id="collapse{{semester.sem}}" class="collapse show" aria-labelledby="{{semester.sem}}" data-parent="#accordion">
            <div class="card-body">

                <table class="table table-bordered">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Code</th>
      <th scope="col">Subject</th>
      <th scope="col">Credits</th>

    </tr>
  </thead>
  <tbody>
    {% for subject in semester.subjects.all%}
    <tr>

      <td>{{subject.code}}</td>
      <td>{{subject.name}}</td>
      <td>{{subject.credit}}</td>
    </tr>
  {% endfor %}

  </tbody>
                </table>

            </div>
          </div>
        </div>

        {% endfor %}
       </div>
   </div>

{% endblock %}

academics/templates/academics/scholarship.html
{% extends 'academics/base.html' %}

{% block content %}
 <h2 class="navy heading">Scholarships</h2>

   <div class="course-desc mt-5">
       <p class="heading">PU Scholarships</p>
       <p class="para ">
          The College provides scholarships to deserving students
           according to PU guidelines. 5% of the annual intake of students
           is provided scholarships in this category.

       </p>
   </div>

<div class="course-desc mt-5">
       <p class="heading">NCIT Scholarships</p>
       <p class="para">
         The College provides scholarships based on the student’s
         combined marks of +2/equivalent and the NCIT Entrance Test.
       </p>
   </div>

<div class="course-desc mt-5">
       <p class="heading">Performance Scholarships</p>
       <p class="para">
          TThe College awards full scholarships (Semester Fees waiver)
           to students who achieve an SGPA of 4 in any Semester for the
           subsequent Semester.
       </p>
    <p class="para">NCIT also awards those students who are class toppers or second- toppers.</p>
</div>

{% endblock%}

academics/templates/academics/side_bar.html
 <ul class="list-group notice-bar " >
                     <ul class="list-group list-group-flush" >
                         <li  class="list-group-item text-danger notice" style="margin-bottom:30px;"><i class="fa fa-bullhorn"></i>&nbsp;Notice Board</li>
                    </ul>
                     {% for notice in side_bar_notices %}

                    <div class="card notice-card">
                       <div class="card-body">
                           <h5 class="card-title">{{notice.heading}}</h5>
                            <p class="text-muted"><em>Posted on : </em>{{notice.date_posted|date:"F d, Y"}}</p>
                            <a href="{{notice.get_absolute_url}}" class="btn btn-primary">View Notice</a>
                       </div>
                    </div>
                    {% endfor %}

                </ul>